const testgrid = [
    [
        { value: null, rowInd: 0, colInd: 0 },
        { value: null, rowInd: 0, colInd: 1 },
        { value: null, rowInd: 0, colInd: 2 },
        { value: "8", rowInd: 0, colInd: 3 },
        { value: null, rowInd: 0, colInd: 4 },
        { value: "7", rowInd: 0, colInd: 5 },
        { value: null, rowInd: 0, colInd: 6 },
        { value: null, rowInd: 0, colInd: 7 },
        { value: null, rowInd: 0, colInd: 8 },
    ],
    [
        { value: "2", rowInd: 1, colInd: 0 },
        { value: "5", rowInd: 1, colInd: 1 },
        { value: "7", rowInd: 1, colInd: 2 },
        { value: null, rowInd: 1, colInd: 3 },
        { value: "4", rowInd: 1, colInd: 4 },
        { value: "9", rowInd: 1, colInd: 5 },
        { value: "1", rowInd: 1, colInd: 6 },
        { value: null, rowInd: 1, colInd: 7 },
        { value: null, rowInd: 1, colInd: 8 },
    ],
    [
        { value: "9", rowInd: 2, colInd: 0 },
        { value: "8", rowInd: 2, colInd: 1 },
        { value: null, rowInd: 2, colInd: 2 },
        { value: null, rowInd: 2, colInd: 3 },
        { value: "3", rowInd: 2, colInd: 4 },
        { value: "1", rowInd: 2, colInd: 5 },
        { value: "2", rowInd: 2, colInd: 6 },
        { value: null, rowInd: 2, colInd: 7 },
        { value: null, rowInd: 2, colInd: 8 },
    ],
    [
        { value: null, rowInd: 3, colInd: 0 },
        { value: "2", rowInd: 3, colInd: 1 },
        { value: null, rowInd: 3, colInd: 2 },
        { value: null, rowInd: 3, colInd: 3 },
        { value: null, rowInd: 3, colInd: 4 },
        { value: null, rowInd: 3, colInd: 5 },
        { value: "3", rowInd: 3, colInd: 6 },
        { value: null, rowInd: 3, colInd: 7 },
        { value: "7", rowInd: 3, colInd: 8 },
    ],
    [
        { value: null, rowInd: 4, colInd: 0 },
        { value: null, rowInd: 4, colInd: 1 },
        { value: "8", rowInd: 4, colInd: 2 },
        { value: null, rowInd: 4, colInd: 3 },
        { value: "6", rowInd: 4, colInd: 4 },
        { value: "2", rowInd: 4, colInd: 5 },
        { value: "5", rowInd: 4, colInd: 6 },
        { value: "1", rowInd: 4, colInd: 7 },
        { value: "4", rowInd: 4, colInd: 8 },
    ],
    [
        { value: "5", rowInd: 5, colInd: 0 },
        { value: null, rowInd: 5, colInd: 1 },
        { value: "1", rowInd: 5, colInd: 2 },
        { value: "3", rowInd: 5, colInd: 3 },
        { value: "7", rowInd: 5, colInd: 4 },
        { value: null, rowInd: 5, colInd: 5 },
        { value: "8", rowInd: 5, colInd: 6 },
        { value: null, rowInd: 5, colInd: 7 },
        { value: "9", rowInd: 5, colInd: 8 },
    ],
    [
        { value: null, rowInd: 6, colInd: 0 },
        { value: "3", rowInd: 6, colInd: 1 },
        { value: null, rowInd: 6, colInd: 2 },
        { value: "4", rowInd: 6, colInd: 3 },
        { value: "9", rowInd: 6, colInd: 4 },
        { value: "6", rowInd: 6, colInd: 5 },
        { value: null, rowInd: 6, colInd: 6 },
        { value: null, rowInd: 6, colInd: 7 },
        { value: null, rowInd: 6, colInd: 8 },
    ],
    [
        { value: null, rowInd: 7, colInd: 0 },
        { value: "9", rowInd: 7, colInd: 1 },
        { value: "6", rowInd: 7, colInd: 2 },
        { value: "7", rowInd: 7, colInd: 3 },
        { value: null, rowInd: 7, colInd: 4 },
        { value: null, rowInd: 7, colInd: 5 },
        { value: "4", rowInd: 7, colInd: 6 },
        { value: "8", rowInd: 7, colInd: 7 },
        { value: null, rowInd: 7, colInd: 8 },
    ],
    [
        { value: "7", rowInd: 8, colInd: 0 },
        { value: null, rowInd: 8, colInd: 1 },
        { value: null, rowInd: 8, colInd: 2 },
        { value: null, rowInd: 8, colInd: 3 },
        { value: null, rowInd: 8, colInd: 4 },
        { value: null, rowInd: 8, colInd: 5 },
        { value: null, rowInd: 8, colInd: 6 },
        { value: null, rowInd: 8, colInd: 7 },
        { value: null, rowInd: 8, colInd: 8 },
    ],
];
export default testgrid;
