const testgrid = [
    [
        {
            value: "8",
            rowInd: 0,
            colInd: 0,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 1,
            srow: 1,
            scol: 1,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 0,
            colInd: 1,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 1,
            srow: 1,
            scol: 1,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 0,
            colInd: 2,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 1,
            srow: 1,
            scol: 1,
            impossibles: [],
        },
        {
            value: "3",
            rowInd: 0,
            colInd: 3,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 2,
            srow: 1,
            scol: 2,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 0,
            colInd: 4,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 2,
            srow: 1,
            scol: 2,
            impossibles: [],
        },
        {
            value: "9",
            rowInd: 0,
            colInd: 5,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 2,
            srow: 1,
            scol: 2,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 0,
            colInd: 6,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 3,
            srow: 1,
            scol: 3,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 0,
            colInd: 7,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 3,
            srow: 1,
            scol: 3,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 0,
            colInd: 8,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 3,
            srow: 1,
            scol: 3,
            impossibles: [],
        },
    ],
    [
        {
            value: "9",
            rowInd: 1,
            colInd: 0,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 1,
            srow: 1,
            scol: 1,
            impossibles: [],
        },
        {
            value: "6",
            rowInd: 1,
            colInd: 1,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 1,
            srow: 1,
            scol: 1,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 1,
            colInd: 2,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 1,
            srow: 1,
            scol: 1,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 1,
            colInd: 3,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 2,
            srow: 1,
            scol: 2,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 1,
            colInd: 4,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 2,
            srow: 1,
            scol: 2,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 1,
            colInd: 5,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 2,
            srow: 1,
            scol: 2,
            impossibles: [],
        },
        {
            value: "5",
            rowInd: 1,
            colInd: 6,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 3,
            srow: 1,
            scol: 3,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 1,
            colInd: 7,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 3,
            srow: 1,
            scol: 3,
            impossibles: [],
        },
        {
            value: "3",
            rowInd: 1,
            colInd: 8,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 3,
            srow: 1,
            scol: 3,
            impossibles: [],
        },
    ],
    [
        {
            value: "",
            rowInd: 2,
            colInd: 0,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 1,
            srow: 1,
            scol: 1,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 2,
            colInd: 1,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 1,
            srow: 1,
            scol: 1,
            impossibles: [],
        },
        {
            value: "7",
            rowInd: 2,
            colInd: 2,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 1,
            srow: 1,
            scol: 1,
            impossibles: [],
        },
        {
            value: "2",
            rowInd: 2,
            colInd: 3,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 2,
            srow: 1,
            scol: 2,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 2,
            colInd: 4,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 2,
            srow: 1,
            scol: 2,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 2,
            colInd: 5,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 2,
            srow: 1,
            scol: 2,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 2,
            colInd: 6,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 3,
            srow: 1,
            scol: 3,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 2,
            colInd: 7,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 3,
            srow: 1,
            scol: 3,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 2,
            colInd: 8,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 3,
            srow: 1,
            scol: 3,
            impossibles: [],
        },
    ],
    [
        {
            value: "",
            rowInd: 3,
            colInd: 0,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 4,
            srow: 2,
            scol: 1,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 3,
            colInd: 1,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 4,
            srow: 2,
            scol: 1,
            impossibles: [],
        },
        {
            value: "6",
            rowInd: 3,
            colInd: 2,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 4,
            srow: 2,
            scol: 1,
            impossibles: [],
        },
        {
            value: "4",
            rowInd: 3,
            colInd: 3,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 5,
            srow: 2,
            scol: 2,
            impossibles: [],
        },
        {
            value: "2",
            rowInd: 3,
            colInd: 4,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 5,
            srow: 2,
            scol: 2,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 3,
            colInd: 5,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 5,
            srow: 2,
            scol: 2,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 3,
            colInd: 6,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 6,
            srow: 2,
            scol: 3,
            impossibles: [],
        },
        {
            value: "1",
            rowInd: 3,
            colInd: 7,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 6,
            srow: 2,
            scol: 3,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 3,
            colInd: 8,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 6,
            srow: 2,
            scol: 3,
            impossibles: [],
        },
    ],
    [
        {
            value: "",
            rowInd: 4,
            colInd: 0,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 4,
            srow: 2,
            scol: 1,
            impossibles: [],
        },
        {
            value: "2",
            rowInd: 4,
            colInd: 1,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 4,
            srow: 2,
            scol: 1,
            impossibles: [],
        },
        {
            value: "4",
            rowInd: 4,
            colInd: 2,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 4,
            srow: 2,
            scol: 1,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 4,
            colInd: 3,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 5,
            srow: 2,
            scol: 2,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 4,
            colInd: 4,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 5,
            srow: 2,
            scol: 2,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 4,
            colInd: 5,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 5,
            srow: 2,
            scol: 2,
            impossibles: [],
        },
        {
            value: "7",
            rowInd: 4,
            colInd: 6,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 6,
            srow: 2,
            scol: 3,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 4,
            colInd: 7,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 6,
            srow: 2,
            scol: 3,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 4,
            colInd: 8,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 6,
            srow: 2,
            scol: 3,
            impossibles: [],
        },
    ],
    [
        {
            value: "",
            rowInd: 5,
            colInd: 0,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 4,
            srow: 2,
            scol: 1,
            impossibles: [],
        },
        {
            value: "7",
            rowInd: 5,
            colInd: 1,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 4,
            srow: 2,
            scol: 1,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 5,
            colInd: 2,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 4,
            srow: 2,
            scol: 1,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 5,
            colInd: 3,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 5,
            srow: 2,
            scol: 2,
            impossibles: [],
        },
        {
            value: "8",
            rowInd: 5,
            colInd: 4,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 5,
            srow: 2,
            scol: 2,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 5,
            colInd: 5,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 5,
            srow: 2,
            scol: 2,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 5,
            colInd: 6,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 6,
            srow: 2,
            scol: 3,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 5,
            colInd: 7,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 6,
            srow: 2,
            scol: 3,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 5,
            colInd: 8,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 6,
            srow: 2,
            scol: 3,
            impossibles: [],
        },
    ],
    [
        {
            value: "",
            rowInd: 6,
            colInd: 0,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 7,
            srow: 3,
            scol: 1,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 6,
            colInd: 1,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 7,
            srow: 3,
            scol: 1,
            impossibles: [],
        },
        {
            value: "1",
            rowInd: 6,
            colInd: 2,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 7,
            srow: 3,
            scol: 1,
            impossibles: [],
        },
        {
            value: "7",
            rowInd: 6,
            colInd: 3,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 8,
            srow: 3,
            scol: 2,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 6,
            colInd: 4,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 8,
            srow: 3,
            scol: 2,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 6,
            colInd: 5,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 8,
            srow: 3,
            scol: 2,
            impossibles: [],
        },
        {
            value: "8",
            rowInd: 6,
            colInd: 6,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 9,
            srow: 3,
            scol: 3,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 6,
            colInd: 7,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 9,
            srow: 3,
            scol: 3,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 6,
            colInd: 8,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 9,
            srow: 3,
            scol: 3,
            impossibles: [],
        },
    ],
    [
        {
            value: "7",
            rowInd: 7,
            colInd: 0,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 7,
            srow: 3,
            scol: 1,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 7,
            colInd: 1,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 7,
            srow: 3,
            scol: 1,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 7,
            colInd: 2,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 7,
            srow: 3,
            scol: 1,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 7,
            colInd: 3,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 8,
            srow: 3,
            scol: 2,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 7,
            colInd: 4,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 8,
            srow: 3,
            scol: 2,
            impossibles: [],
        },
        {
            value: "8",
            rowInd: 7,
            colInd: 5,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 8,
            srow: 3,
            scol: 2,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 7,
            colInd: 6,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 9,
            srow: 3,
            scol: 3,
            impossibles: [],
        },
        {
            value: "6",
            rowInd: 7,
            colInd: 7,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 9,
            srow: 3,
            scol: 3,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 7,
            colInd: 8,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 9,
            srow: 3,
            scol: 3,
            impossibles: [],
        },
    ],
    [
        {
            value: "",
            rowInd: 8,
            colInd: 0,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 7,
            srow: 3,
            scol: 1,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 8,
            colInd: 1,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 7,
            srow: 3,
            scol: 1,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 8,
            colInd: 2,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 7,
            srow: 3,
            scol: 1,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 8,
            colInd: 3,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 8,
            srow: 3,
            scol: 2,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 8,
            colInd: 4,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 8,
            srow: 3,
            scol: 2,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 8,
            colInd: 5,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 8,
            srow: 3,
            scol: 2,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 8,
            colInd: 6,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 9,
            srow: 3,
            scol: 3,
            impossibles: [],
        },
        {
            value: "",
            rowInd: 8,
            colInd: 7,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 9,
            srow: 3,
            scol: 3,
            impossibles: [],
        },
        {
            value: "4",
            rowInd: 8,
            colInd: 8,
            possibles: ["1", "2", "3", "4", "5", "6", "7", "8", "9"],
            square: 9,
            srow: 3,
            scol: 3,
            impossibles: [],
        },
    ],
];
export default testgrid;
